[tools]
apko = "latest"
atuin = "latest"
bat = "latest"
chezmoi = "latest"
fd = "latest"
fzf = "latest"
gitconfig = "latest"
github-cli = "latest"
"github:gitbutlerapp/grit" = "latest"
"github:sinelaw/fresh" = "latest"
herdr = "latest"
hk = "latest"
hunk = "latest"
java = "latest"
node = "latest"
opencode = "latest"
pi = "latest"
"pipx:commitizen" = "latest"
"pipx:gnome-extensions-cli" = "latest"
ripgrep = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
wait-for-gh-rate-limit = "latest"

[settings]
experimental = true
lockfile = true
