[tools]
apko = "latest"
atuin = "latest"
bat = "latest"
chezmoi = "latest"
fd = "latest"
gitconfig = "latest"
github-cli = "latest"
"github:sinelaw/fresh" = "latest"
herdr = "latest"
hk = "latest"
hunk = "latest"
opencode = "latest"
pi = "latest"
"pipx:commitizen" = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"

[settings]
experimental = true
